apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: keycloak-
resources:
- deployment.yaml
- sa.yaml
images:
- name: ghcr.io/doodlescheduling/keycloak-controller
  newTag: v1.1.0
