apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: k8skeycloak-
resources:
- deployment.yaml
- sa.yaml
images:
- name: ghcr.io/doodlescheduling/k8skeycloak-controller
  newTag: v1.0.0
