{{- if .Values.clusterRBAC.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "keycloak-controller.fullname" . }}-reconcile-proxy
rules:
- apiGroups: ["keycloak.infra.doodle.com"]
  resources:
  - keycloakrealms
  verbs: ["get"]
- apiGroups: ["keycloak.infra.doodle.com"]
  resources:
  - keycloakrealms/status
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "keycloak-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "keycloak-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "keycloak-controller.chart" . }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
- apiGroups:
  - "keycloak.infra.doodle.com"
  resources:
  - keycloakrealms
  - keycloakclients
  - keycloakusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "keycloak.infra.doodle.com"
  resources:
  - keycloakrealms/status
  - keycloakclients/status
  - keycloakusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
