
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.infra.doodle.com
  resources:
  - keycloakclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.infra.doodle.com
  resources:
  - keycloakclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keycloak.infra.doodle.com
  resources:
  - keycloakrealms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.infra.doodle.com
  resources:
  - keycloakrealms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keycloak.infra.doodle.com
  resources:
  - keycloakusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.infra.doodle.com
  resources:
  - keycloakusers/status
  verbs:
  - get
  - patch
  - update
