apiVersion: v2
appVersion: 0.0.0
description: Keycloak Realm reconciler
home: https://github.com/DoodleScheduling/keycloak-controller
maintainers:
- name: devops
  email: devops@doodle.com
keywords:
- kubernetes-controller
- http-keycloak
- request-clone
name: keycloak-controller
sources:
- https://github.com/DoodleScheduling/keycloak-controller
version: 0.0.0
