{{- if .Values.clusterRBAC.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "k8skeycloak-controller.fullname" . }}-view
  labels:
    app.kubernetes.io/name: {{ include "k8skeycloak-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "k8skeycloak-controller.chart" . }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
- apiGroups:
  - "keycloak.infra.doodle.com"
  resources:
  - keycloakrealms
  - keycloakclients
  - keycloakusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "keycloak.infra.doodle.com"
  resources:
  - keycloakrealms/status
  - keycloakclients/status
  - keycloakusers/status
  verbs:
  - get
{{- end }}
