{{- if .Values.kubeRBACProxy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8skeycloak-controller.fullname" . }}-metrics-reader
  labels:
    app.kubernetes.io/name: {{ include "k8skeycloak-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "k8skeycloak-controller.chart" . }}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8skeycloak-controller.fullname" . }}-metrics
  labels:
    app.kubernetes.io/name: {{ include "k8skeycloak-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "k8skeycloak-controller.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8skeycloak-controller.fullname" . }}-metrics-reader
subjects:
- kind: ServiceAccount
  name: {{ template "k8skeycloak-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8skeycloak-controller.fullname" . }}-proxy
  labels:
    app.kubernetes.io/name: {{ include "k8skeycloak-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "k8skeycloak-controller.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8skeycloak-controller.fullname" . }}-proxy
subjects:
  - kind: ServiceAccount
    name: {{ template "k8skeycloak-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8skeycloak-controller.fullname" . }}-proxy
  labels:
    app.kubernetes.io/name: {{ include "k8skeycloak-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "k8skeycloak-controller.chart" . }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  {{- end }}
