name: e2e

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-ghcache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-ghcache-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
      - name: Setup Kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Setup envtest
        uses: fluxcd/pkg/actions/envtest@main
        with:
          version: "1.19.2"
      - name: Setup Helm
        uses: fluxcd/pkg/actions/helm@main
      - name: Run controller tests
        run: make test
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make test and commit changes'
            exit 1
          fi
      - name: Fetch keycloak-client 
        run: sh scripts/fetch-jars.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        run: |
          make docker-build IMG=test/k8skeycloak-controller:latest BUILD_PLATFORMS=linux/amd64 \
            BUILD_ARGS="--cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max"
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Load test image
        run: kind load docker-image test/k8skeycloak-controller:latest
      - name: Deploy controller
        run: make deploy IMG=test/k8skeycloak-controller:latest
      - name: Setup keycloak
        env:
          KEYCLOAK_VER: ${{ '16.0.4' }}
        run: |
          kubectl create ns keycloak
          helm repo add codecentric https://codecentric.github.io/helm-charts


          cat <<EOT >> values.yaml
          extraEnv: |
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
          EOT

          helm upgrade --wait -i keycloak codecentric/keycloak \
          --version $KEYCLOAK_VER \
          --namespace keycloak \
          -f values.yaml
      - name: Run keycloakrealm tests
        run: |
          kubectl -n k8skeycloak-system apply -f ./config/testdata
          kubectl -n k8skeycloak-system wait keycloakrealm/test --for=condition=Ready --timeout=3m
          kubectl -n keycloak port-forward svc/keycloak-http 8443:8443 &>/dev/null &
          sleep 2
          curl --fail -k https://localhost:8443/auth/realms/test/.well-known/openid-configuration
      - name: Logs
        run: |
          kubectl -n k8skeycloak-system logs deploy/k8skeycloak-controller
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n kube-system describe pods
          kubectl -n k8skeycloak-system describe pods
          kubectl -n k8skeycloak-system describe keycloakrealm
          kubectl -n k8skeycloak-system get keycloakrealm -oyaml
          kubectl -n k8skeycloak-system get secrets -o yaml
          kubectl -n k8skeycloak-system get all
          kubectl -n k8skeycloak-system logs deploy/k8skeycloak-controller
          kubectl -n keycloak get all
