name: pr-command
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  slash-command:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Get shared actions
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      
      - uses: ./.actions/slash-command
        with:
          token: ${{ secrets.GH_ACTIONS }}
