name: pr-deploy
on:
  pull_request:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      commit-author:
        description: The author used for gitops commits
        required: false
        default: "github-actions <actions@users.noreply.github.com>"
      pr-number: 
        description: The pr number which should be deployed
        required: true
jobs:
  build:
    permissions:
      packages: read
      contents: read
      pull-requests: write

    runs-on: [self-hosted, minimalistic]
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout source
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0

      - name: Get shared actions
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
            
      - uses: ./.actions/short-sha
        id: short-sha

      - uses: ./.actions/retag-image
        id: chart-exists
        with:
          lookup: ghcr.io/doodlescheduling/charts/${{ github.event.repository.name }}:0.0.0-SHA${{ steps.short-sha.outputs.ref }}

      - uses: ./.actions/pull-request-labels
        if: ${{ steps.chart-exists.outputs.found == 'true' }}
        id: pr-labels
        with:
          pr-number: ${{ github.event.number || inputs.pr-number }}

      - uses:  ./.actions/deploy-devbox
        if: ${{ steps.pr-labels.outputs.targets != '' }}
        with:
          name: ${{ github.event.repository.name }}
          version: 0.0.0-SHA${{ steps.short-sha.outputs.ref }}
          namespaces: ${{ steps.pr-labels.outputs.targets }}
          devops-svc-ssh-key: ${{ secrets.PRIVATE_SSH_KEY_GITOPS }}
          enable-testframework: ${{ steps.pr-labels.outputs.run-tests }}
          testframework-image-tag: ${{ steps.pr-labels.outputs.testframework-image-tag }}
          commit-author: ${{ inputs.commit-author ||  format('{0} <{1}@users.noreply.github.com>', github.actor, github.actor)}}
