name: pr-stale
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: [self-hosted, minimalistic]
    steps:
      - name: Get shared actions
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      - uses: ./.actions/stale
        with:
          repo-token: ${{ secrets.GH_ACTIONS }}
